Repository microsoft/EasyRepro, pull requests merged in 2019-06, with the labels that each got.

#563 Adding UCITestMode option for full UI Testing
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Elements/OnlineLogin.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/WebClient.cs
  Microsoft.Dynamics365.UIAutomation.Browser/BrowserOptions.cs
  Microsoft.Dynamics365.UIAutomation.Sample/TestSettings.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Read/OpenAccount.cs
Labels: enhancement

#570 Add methods to retrieve list of areas and subareas, with tests for each
  Microsoft.Dynamics365.UIAutomation.Api/Pages/Navigation.cs
  Microsoft.Dynamics365.UIAutomation.Sample/Microsoft.Dynamics365.UIAutomation.Sample.csproj
  Microsoft.Dynamics365.UIAutomation.Sample/Web/Navigation/AreasAndSubAreas.cs
Labels: enhancement

#572 Improve Entity.GetSubGridItemsCount
  Microsoft.Dynamics365.UIAutomation.Api/DTOs/ElementReference.cs
  Microsoft.Dynamics365.UIAutomation.Api/Pages/Entity.cs
Labels: enhancement

#573 Read Entity Name of current record (API & UCI)
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Elements/Entity.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/WebClient.cs
  Microsoft.Dynamics365.UIAutomation.Api/Pages/Entity.cs
Labels: enhancement

#574 Entity.GetValue: Throw correct exception when field has different type.
  Microsoft.Dynamics365.UIAutomation.Api/Pages/Entity.cs
Labels: enhancement

#579 Bug fix: DriversPath is not used to find Browser a executable.
  Microsoft.Dynamics365.UIAutomation.Browser/BrowserDriverFactory.cs
Labels: enhancement

#582 GetHeaderValue throwing NoSuchElementException
  Microsoft.Dynamics365.UIAutomation.Api/Pages/Entity.cs
  Microsoft.Dynamics365.UIAutomation.Api/Pages/QuickCreate.cs
Labels: enhancement

#590 Updating RecordWall.WEBTestAddTask() test and underlying ActivityFeed…
  Microsoft.Dynamics365.UIAutomation.Api/Pages/ActivityFeed.cs
  Microsoft.Dynamics365.UIAutomation.Sample/Web/Entity/RecordWall.cs
Labels: bug

#591 Return CommandBar Values and debug error fix for UCI
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Elements/CommandBar.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Elements/OnlineLogin.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/WebClient.cs
  Microsoft.Dynamics365.UIAutomation.Api/Pages/CommandBar.cs
  Microsoft.Dynamics365.UIAutomation.Sample/Microsoft.Dynamics365.UIAutomation.Sample.csproj
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/CommandBar/CommandButton.cs
  Microsoft.Dynamics365.UIAutomation.Sample/Web/CommandBar/CommandButton.cs
Labels: bug, enhancement

#592 Add check to only set Time value if Time field is present
  Microsoft.Dynamics365.UIAutomation.Api/Pages/ActivityFeed.cs
  Microsoft.Dynamics365.UIAutomation.Sample/Web/Entity/RecordWall.cs
Labels: bug

#589 Added GetHeaderOptionValues and GetOptionValues to Entity
  Microsoft.Dynamics365.UIAutomation.Api/Pages/Entity.cs
Labels: enhancement

#594 Issues with WebClient Lookup fields and Firefox browser
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Microsoft.Dynamics365.UIAutomation.Api.UCI.csproj
  Microsoft.Dynamics365.UIAutomation.Api.UCI/packages.config
  Microsoft.Dynamics365.UIAutomation.Api/Microsoft.Dynamics365.UIAutomation.Api.csproj
  Microsoft.Dynamics365.UIAutomation.Api/Pages/Entity.cs
  Microsoft.Dynamics365.UIAutomation.Api/Pages/GuidedHelp.cs
  Microsoft.Dynamics365.UIAutomation.Api/Pages/Navigation.cs
  Microsoft.Dynamics365.UIAutomation.Api/XrmPage.cs
  Microsoft.Dynamics365.UIAutomation.Api/packages.config
  Microsoft.Dynamics365.UIAutomation.Browser/Microsoft.Dynamics365.UIAutomation.Browser.csproj
  Microsoft.Dynamics365.UIAutomation.Browser/packages.config
  Microsoft.Dynamics365.UIAutomation.Sample/Microsoft.Dynamics365.UIAutomation.Sample.csproj
  Microsoft.Dynamics365.UIAutomation.Sample/Web/Update/UpdateAccount.cs
  Microsoft.Dynamics365.UIAutomation.Sample/packages.config
Labels: bug
