Repository microsoft/EasyRepro, pull requests merged in 2020-05, with the labels that each got.

#844 Add Support for Access "More Command" on RelatedGrid CommandBar
  Microsoft.Dynamics365.UIAutomation.Api.UCI/DTO/AppElementReference.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Elements/RelatedGrid.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/WebClient.cs
Labels: enhancement

#847 Update Entity_RecordSetNavList reference to the proper element
  Microsoft.Dynamics365.UIAutomation.Api.UCI/DTO/AppElementReference.cs
Labels: bug

#845 PublishDialog, SetStateDialog, and GetFormNotifications fixes
  Microsoft.Dynamics365.UIAutomation.Api.UCI/DTO/AppElementReference.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/DTO/FormNotification.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/DTO/FormNotificationType.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Elements/Dialog.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/WebClient.cs
Labels: enhancement

#848 Lookup & Quick Create Fixes
  Microsoft.Dynamics365.UIAutomation.Api.UCI/DTO/AppElementReference.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/DTO/FormContextType.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Elements/BusinessProcessFlow.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Elements/Entity.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Elements/QuickCreate.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Elements/Timeline.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Microsoft.Dynamics365.UIAutomation.Api.UCI.csproj
  Microsoft.Dynamics365.UIAutomation.Api.UCI/WebClient.cs
  Microsoft.Dynamics365.UIAutomation.Api/Pages/BusinessProcessFlow.cs
  Microsoft.Dynamics365.UIAutomation.Api/Pages/QuickCreate.cs
Labels: bug

#850 GetBusinessProcessError method for Unified Interface
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Elements/Entity.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/WebClient.cs
Labels: enhancement

#853 Include field label as part of GetField() method
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Controls/Field.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/DTO/AppElementReference.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/WebClient.cs
Labels: enhancement

#856 Update DateTimeControl.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Controls/DateTimeControl.cs
Labels: bug

#859 RelatedGrid Fixes
  Microsoft.Dynamics365.UIAutomation.Api.UCI/DTO/AppElementReference.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Elements/RelatedGrid.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/WebClient.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/SetValue.cs
Labels: bug

#866 Add FormContext to SetValue within Timeline controls to address #865
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Elements/Timeline.cs
Labels: bug

#864 Changes to support Entity SubGrids
  Microsoft.Dynamics365.UIAutomation.Api.UCI/DTO/AppElementReference.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/DTO/ElementReference.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Elements/CommandBar.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Elements/Dashboard.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Elements/Entity.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Elements/Grid.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Elements/RelatedGrid.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Elements/Subgrid.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Elements/Timeline.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Microsoft.Dynamics365.UIAutomation.Api.UCI.csproj
  Microsoft.Dynamics365.UIAutomation.Api.UCI/WebClient.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/XrmApp.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Delete/DeleteAccount.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Delete/DeleteCase.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Delete/DeleteContact.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Delete/DeleteLead.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Delete/DeleteOpportunity.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Read/OpenAccount.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Read/OpenContact.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Timeline/AddActivity.cs
  Microsoft.Dynamics365.UIAutomation.Sample/Web/Create/CreateCase.cs
Labels: bug, enhancement

#875 Fixes for CommandBar.ClickCommand()
  Microsoft.Dynamics365.UIAutomation.Api.UCI/WebClient.cs
Labels: bug
