Repository microsoft/EasyRepro, pull requests merged in 2020-03, with the labels that each got.

#776 Enable Traces by default in Samples Project (related to #775)
  Microsoft.Dynamics365.UIAutomation.Browser/Logs/StringFormater.cs
  Microsoft.Dynamics365.UIAutomation.Browser/Logs/TracingService.cs
  Microsoft.Dynamics365.UIAutomation.Browser/Microsoft.Dynamics365.UIAutomation.Browser.csproj
  Microsoft.Dynamics365.UIAutomation.Sample/ConsoleTraceListener.cs
  Microsoft.Dynamics365.UIAutomation.Sample/Microsoft.Dynamics365.UIAutomation.Sample.csproj
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/ApiTests/TestsBase_Tests.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Controls/Grid.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/TestsBase.cs
  Microsoft.Dynamics365.UIAutomation.Sample/app.config
Labels: enhancement

#787 Added support for flip switch control #786
  Microsoft.Dynamics365.UIAutomation.Api.UCI/DTO/AppElementReference.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/WebClient.cs
Labels: bug

#789 Replace all instances of 'mfaSecrectKey' with 'mfaSecretKey'
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Elements/OnlineLogin.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/WebClient.cs
  Microsoft.Dynamics365.UIAutomation.Sample/SharedAPI/AzureInsights/UploadTelemetryUCI.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Controls/Grid.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Create/CreateActivity.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Create/CreateCase.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Create/CreateContact.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Create/CreateOpportunity.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Delete/DeleteAccount.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Delete/DeleteCase.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Delete/DeleteContact.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Delete/DeleteLead.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Delete/DeleteOpportunity.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/GlobalSearch/GlobalRelevanceSearch.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Navigation/FormSelector.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Navigation/GlobalSearch.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Navigation/PortalAdmin.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/QuickCreate/QuickCreate.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/QuickStart/1_Demo_TestsClass.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/QuickStart/2_Demo_Let_TestsBase_WorkForYou_ReadConfigParameters.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Read/HighlightAccount.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Read/OpenContact.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Read/OpenLead.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Read/OpenOpportunity.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/SetValue.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/SpecialConfigurationTests/RandomAccountTest.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/TestsBase.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Timeline/AddActivity.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Timeline/AddNote.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Timeline/AddPost.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Update/UpdateAccount.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Update/UpdateCase.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Update/UpdateContact.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Update/UpdateLead.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Update/UpdateOpportunity.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/Validate/CheckFieldRequired.cs
  Microsoft.Dynamics365.UIAutomation.Sample/app.build.config
  Microsoft.Dynamics365.UIAutomation.Sample/app.config
  README.md
Labels: formatting

#783 Get form notifications on a form
  Microsoft.Dynamics365.UIAutomation.Api.UCI/DTO/AppElementReference.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/DTO/FormNotification.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/DTO/FormNotificationType.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Elements/Entity.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Microsoft.Dynamics365.UIAutomation.Api.UCI.csproj
  Microsoft.Dynamics365.UIAutomation.Api.UCI/WebClient.cs
  Microsoft.Dynamics365.UIAutomation.Sample/Microsoft.Dynamics365.UIAutomation.Sample.csproj
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/FormNotifications/ReadFormNotifications.cs
Labels: enhancement

#792 Add MFA Secret instructions to README.md
  README.md
Labels: formatting

#793 Removed failure callback from TryToClickInAppTile()
  Microsoft.Dynamics365.UIAutomation.Api.UCI/WebClient.cs
  Microsoft.Dynamics365.UIAutomation.Sample/UCI/TestsBase.cs
Labels: bug
