Repository microsoft/EasyRepro, pull requests merged in 2021-02, with the labels that each got.

#1053 Fix id reading for get grid items
  Microsoft.Dynamics365.UIAutomation.Api.UCI/WebClient.cs
Labels: enhancement

#1067 Fix Field.IsReadOnly for an input field
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Controls/Field.cs
Labels: bug

#1068 Fix open Performance Widget when performance issues exist
  Microsoft.Dynamics365.UIAutomation.Api.UCI/DTO/AppElementReference.cs
Labels: enhancement

#1070 Fix Remove Lookup Value when quickly clear many lookup fields
  Microsoft.Dynamics365.UIAutomation.Api.UCI/WebClient.cs
Labels: bug

#1085 Dev/zwuai/uci open app fix
  Microsoft.Dynamics365.UIAutomation.Api.UCI/WebClient.cs
Labels: bug

#1090 fix for issue 1087 due to recent release of Dynamics 365 (commandbar …
  Microsoft.Dynamics365.UIAutomation.Api.UCI/WebClient.cs
Labels: bug

#1089 Update webclient for mfa validation
  Microsoft.Dynamics365.UIAutomation.Api.UCI/WebClient.cs
Labels: bug

#1093 Fix for subgrid click command (issue 1087)
  Microsoft.Dynamics365.UIAutomation.Api.UCI/WebClient.cs
Labels: bug

#1094 Fix for subgrid click command overflow (issue 1087)
  Microsoft.Dynamics365.UIAutomation.Api.UCI/DTO/AppElementReference.cs
Labels: bug

#1095 fix: related grid commands and quick create menu items
  Microsoft.Dynamics365.UIAutomation.Api.UCI/DTO/AppElementReference.cs
Labels: bug

#1097 Updated Field.ReadOnly to work for textarea elements
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Controls/Field.cs
Labels: bug

#1100 Resolved dialog context not found and added feature select tab and click command on dialog
  Microsoft.Dynamics365.UIAutomation.Api.UCI/DTO/AppElementReference.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Elements/Dialog.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/Elements/Entity.cs
  Microsoft.Dynamics365.UIAutomation.Api.UCI/WebClient.cs
Labels: bug, enhancement
